---
name: latest
version: 0.03
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Use the latest Perl features
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=latest
  license: http://dev.perl.org/licenses/
  repository: git://github.com/AndyA/latest.git
requires:
  Test::More: 0
  version: 0
provides:
  latest:
    file: lib/latest.pm
    version: 0.03
  latest::feature:
    file: lib/latest.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
